import React, { useState } from 'react';
import { useFarm } from '../context/FarmContext';
import { Reminder, AlertPriority } from '../types';
import {
  Bell,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  Clock,
  Sparkles,
  ChevronRight,
  Filter,
  CheckCheck,
  Calendar,
  Wheat,
  MapPin
} from 'lucide-react';

export const RemindersView: React.FC = () => {
  const {
    reminders,
    unreadRemindersCount,
    markReminderAsRead,
    markAllRemindersAsRead,
    farms,
    crops,
    activities,
    updateActivityStatus,
    setActiveTab
  } = useFarm();

  const [filterPriority, setFilterPriority] = useState<string>('ALL');
  const [filterRead, setFilterRead] = useState<'ALL' | 'UNREAD' | 'READ'>('ALL');

  const filteredReminders = reminders.filter(r => {
    if (filterPriority !== 'ALL' && r.priority !== filterPriority) return false;
    if (filterRead === 'UNREAD' && r.isRead) return false;
    if (filterRead === 'READ' && !r.isRead) return false;
    return true;
  });

  const getPriorityStyle = (priority: AlertPriority) => {
    switch (priority) {
      case 'CRITICAL':
        return {
          badge: 'bg-rose-600 text-white',
          card: 'bg-rose-50/50 border-rose-300',
          icon: 'text-rose-600'
        };
      case 'HIGH':
        return {
          badge: 'bg-amber-600 text-white',
          card: 'bg-amber-50/50 border-amber-300',
          icon: 'text-amber-600'
        };
      case 'MEDIUM':
        return {
          badge: 'bg-lime-700 text-white',
          card: 'bg-lime-50/40 border-lime-300',
          icon: 'text-lime-700'
        };
      default:
        return {
          badge: 'bg-stone-600 text-white',
          card: 'bg-stone-50 border-stone-200',
          icon: 'text-stone-600'
        };
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-lime-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-2 bg-amber-100 text-amber-800 rounded-lg">
              <Bell className="w-5 h-5" />
            </span>
            <h1 className="text-2xl font-extrabold text-emerald-950 font-serif">Smart Notifications & Rule Advisories</h1>
          </div>
          <p className="text-xs sm:text-sm text-stone-600 mt-1">
            Automated alerts generated by the deterministic engine comparing field task schedules against weather thresholds.
          </p>
        </div>

        <button
          id="mark-all-read-btn"
          onClick={markAllRemindersAsRead}
          className="flex items-center gap-1.5 bg-white hover:bg-lime-50 text-emerald-900 font-bold px-4 py-2 rounded-xl border border-lime-300 shadow-xs transition text-xs cursor-pointer"
        >
          <CheckCheck className="w-4 h-4 text-emerald-700" />
          <span>Mark All as Read</span>
        </button>
      </div>

      {/* Filter Tabs */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white p-3.5 rounded-xl border border-lime-200 shadow-2xs">
        <div className="flex items-center space-x-1 overflow-x-auto">
          {(['ALL', 'UNREAD', 'READ'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setFilterRead(tab)}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition capitalize ${
                filterRead === tab
                  ? 'bg-emerald-800 text-white shadow-xs'
                  : 'text-stone-600 hover:text-emerald-950 hover:bg-lime-50'
              }`}
            >
              {tab === 'ALL' ? `All Alerts (${reminders.length})` : tab === 'UNREAD' ? `Unread (${unreadRemindersCount})` : 'Read'}
            </button>
          ))}
        </div>

        <div className="flex items-center space-x-2 text-xs">
          <span className="text-stone-500 font-semibold">Priority:</span>
          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            className="bg-stone-50 border border-stone-300 rounded-lg px-2.5 py-1.5 text-xs font-medium text-emerald-950 focus:outline-none focus:ring-1 focus:ring-emerald-700"
          >
            <option value="ALL">All Priorities</option>
            <option value="CRITICAL">🔴 Critical Priority</option>
            <option value="HIGH">🟠 High Priority</option>
            <option value="MEDIUM">🟢 Medium Priority</option>
            <option value="LOW">⚪ Low Priority</option>
          </select>
        </div>
      </div>

      {/* List of Reminders */}
      <div className="space-y-3">
        {filteredReminders.length === 0 ? (
          <div className="text-center py-12 bg-white rounded-2xl border border-dashed border-lime-300 p-6">
            <CheckCircle2 className="w-10 h-10 text-emerald-600 mx-auto mb-2 opacity-60" />
            <h3 className="text-base font-bold text-emerald-950">Inbox Zero</h3>
            <p className="text-xs text-stone-500 mt-1 max-w-sm mx-auto">
              No matching reminders found. The deterministic engine will notify you when tasks are due or weather conflicts arise.
            </p>
          </div>
        ) : (
          filteredReminders.map((rem) => {
            const style = getPriorityStyle(rem.priority);
            const linkedFarm = farms.find(f => f.id === rem.farmId);
            const linkedCrop = crops.find(c => c.id === rem.cropId);
            const linkedActivity = activities.find(a => a.id === rem.activityId);

            return (
              <div
                key={rem.id}
                className={`rounded-2xl border p-4.5 shadow-xs transition flex flex-col md:flex-row md:items-center justify-between gap-4 ${style.card} ${
                  !rem.isRead ? 'ring-1 ring-lime-400' : 'opacity-85'
                }`}
              >
                <div className="space-y-1.5 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className={`text-[10px] font-extrabold uppercase px-2 py-0.5 rounded font-mono ${style.badge}`}>
                      {rem.priority}
                    </span>
                    <span className="text-[10px] bg-white/80 border border-stone-200 text-stone-700 font-bold px-2 py-0.5 rounded uppercase">
                      {rem.ruleCode.replace(/_/g, ' ')}
                    </span>
                    <span className="text-xs text-stone-500">
                      📅 {rem.triggerDate}
                    </span>
                    {!rem.isRead && (
                      <span className="text-[10px] bg-emerald-800 text-lime-300 font-bold px-1.5 py-0.2 rounded">
                        NEW
                      </span>
                    )}
                  </div>

                  <h3 className="text-base font-bold text-emerald-950">{rem.title}</h3>
                  <p className="text-xs text-stone-700 leading-relaxed">{rem.message}</p>

                  {(linkedFarm || linkedCrop) && (
                    <div className="flex flex-wrap items-center gap-3 pt-1 text-xs text-stone-600">
                      {linkedFarm && (
                        <span className="flex items-center gap-1">
                          <MapPin className="w-3.5 h-3.5 text-emerald-700" />
                          Plot: <strong>{linkedFarm.farmName}</strong>
                        </span>
                      )}
                      {linkedCrop && (
                        <span className="flex items-center gap-1">
                          <Wheat className="w-3.5 h-3.5 text-emerald-700" />
                          Crop: <strong>{linkedCrop.cropName}</strong>
                        </span>
                      )}
                    </div>
                  )}
                </div>

                {/* Right Action Buttons */}
                <div className="flex flex-wrap items-center gap-2 shrink-0 pt-2 md:pt-0 border-t md:border-t-0 border-stone-200">
                  {linkedActivity && linkedActivity.status === 'PENDING' && (
                    <button
                      onClick={() => {
                        updateActivityStatus(linkedActivity.id, 'COMPLETED');
                        markReminderAsRead(rem.id);
                      }}
                      className="bg-emerald-800 hover:bg-emerald-900 text-white font-bold px-3 py-1.5 rounded-lg text-xs transition shadow-xs cursor-pointer"
                    >
                      Complete Task
                    </button>
                  )}

                  {!rem.isRead ? (
                    <button
                      onClick={() => markReminderAsRead(rem.id)}
                      className="bg-white hover:bg-lime-50 text-emerald-900 font-semibold px-3 py-1.5 rounded-lg text-xs border border-lime-300 transition cursor-pointer"
                    >
                      Mark Read
                    </button>
                  ) : (
                    <span className="text-[11px] text-stone-500 italic pr-2">Read</span>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
